name: .NET Core

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: deploy to portainer
      uses: LGinC/portainer-stack-deploy@master
      with: 
        serverurl: http://1065.cloud:8862
        username: ${{ secrets.PORTAINER_USERNAME }}
        password: ${{ secrets.PORTAINER_PASSWORD }}
        endpointId: 1
        stackname: destinyapi
        imagename: 18790997531/destinycore:latest
        docker_compose: |
          version: "2"
          services:
            destinyapi:
              image:  18790997531/destinycore
              container_name: DestinyFlowAPI_From_GithubAction             
              ports:
              - 5000:80
              volumes:
              - /home/wzw/DestinyCore/DestinyFlow/DestinyCoreDb.txt:/app/DestinyCoreDb.txt
              - /home/wzw/DestinyCore/DestinyFlow/DestinyCoreRedis.txt:/app/DestinyCoreRedis.txt
                
#    - name: Test
#      run: dotnet test --no-restore --verbosity normal
